baseURL: "https://minyeamer.github.io/"
title: "Minystory"
description: "minyeamer's blog"
theme: "Book"
languageCode: "ko-kr"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
  disableXML: true
  minifyOutput: true

params:
  author: "minyeamer"
  # author: ["Me", "You"] # multiple authors
  keywords: ["minyeamer", "Blog", "Data", "Engineering", "MLOps", "미니스토리", "블로그"]

  favicon: "/images/favicon.ico"
  images:
    - "/images/profile/opengraph.jpg"

  assets:
    favicon: "/images/favicons/favicon.ico"
    favicon16x16: "/images/favicons/favicon-16x16.png"
    favicon32x32: "/images/favicons/favicon-32x32.png"
    apple_touch_icon: "/images/favicons/apple-touch-icon.png"
    safari_pinned_tab: "/images/favicons/apple-touch-icon.png"

  BookMenu:
    profileImage: "/images/profile/menu.jpg"
    githubLink: "https://github.com/minyeamer"
    categoriesLabel: "전체"
    recentPosts: true

  BookComments:
    enable: true
    disqusShortname: "minyeamer"

  GoogleAnalytics:
    tagId: "G-BJ8Z9RMBPJ"

  SearchEngine:
    google:
      SiteVerificationTag: "u1tWcHmHUZWfFT1cHaku6sqU-bK40N3WLR-C-4VUWN0"
    naver:
      SiteVerificationTag: "6eaf8e9da1a6104780f056f1a7797fe5a3a5a0da"
    # bing:
    #   SiteVerificationTag: "XYZabc"
    # yandex:
    #   SiteVerificationTag: "XYZabc"

  schema:
    publisherType: "Person"
    sameAs:
      - "https://minyeamer.tistory.com/"
      - "https://velog.io/@minyeamer/posts"

  social:
    twitter: "https://x.com/minyeamer"

markup:
  goldmark:
    extensions:
      typographer:
        disable: true
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    codeFences: true
  tableOfContents:
    startLevel: 2
    endLevel: 3

permalinks:
  posts: "/blog/:slugorcontentbasename/"

ignoreFiles: ["_page.md", "README.md"]
